### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by alexmick** [jctissier/Euro2016_TerminalApp#3]
Hi there, first thanks for this cool app ! So useful to follow the cup ⚽ 

As you said you are open to suggestions, one thing you might want to consider for any python app is to add a [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files) to bundle all you pip dependencies and install them in one go with `pip install -r requirements.txt`
The install process will be simplified 😉

**Comment by jctissier** [comment]
Hey Alex, thanks for the feedback!

I didn't know that was possible, so I will definitely get on that and add it in the update! Let me know if there is anything else that you feel could make the program smoother 😄

**Comment by stvhwrd** [comment]
Good idea @alexmick, issue #3 resolved with pull request #6
