### ISSUE TITLE
Group names displayed incorrectly

### ISSUE THREAD

**Issue by stvhwrd** [jctissier/Euro2016_TerminalApp#4]
All group names are displayed as "GroupA" when displaying standings by "all"

<img width="617" alt="screen shot 2016-06-23 at 8 50 32 am" src="https://cloud.githubusercontent.com/assets/4117011/16310014/a070d5ec-391f-11e6-8e39-ccb615f46008.png">

**Comment by jctissier** [comment]
Thank you for letting me know! I'll fix the bug tonight and get back to you

**Comment by stvhwrd** [comment]
Happy to help!
